kv:
  mode: raft 
  codec: json

logger:
  level: debug 

listener:
  addr: 0.0.0.0:5001

raft:
  cluster:
    self_id: kv-0 
    nodes:
      - id: kv-0
        addr: kv-0:5001
      - id: kv-1 
        addr: kv-1:5001
      - id: kv-2 
        addr: kv-2:5001

  runtime:
    heartbeat_interval: 100ms
    election_timeout_min: 500ms
    election_timeout_max: 1s

  transport:
    request_timeout: 300ms
