services:
  raft-0:
    profiles: ["cluster"]
    image: ${RAFTD_TAG}
    environment:
      RAFT_SELF_ID: raft-0
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./raftd_config.yml:/etc/raft/config.yml:ro
    
  raft-1:
    profiles: ["cluster"]
    image: ${RAFTD_TAG}
    environment:
      RAFT_SELF_ID: raft-1
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./raftd_config.yml:/etc/raft/config.yml:ro

  raft-2:
    profiles: ["cluster"]
    image: ${RAFTD_TAG}
    environment:
      RAFT_SELF_ID: raft-2
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./raftd_config.yml:/etc/raft/config.yml:ro

  raftctl:
    profiles: ["manual"]
    image: ${RAFTCTL_TAG}
    environment:
      RAFT_ADDR: raft-0:5001
    command: ["/bin/sh"]
    stdin_open: true
    tty: true
