logger:
  level: debug 

listener:
  addr: 0.0.0.0:5001

raft:
  cluster:
    self_id: raft-0 
    nodes:
      - id: raft-0
        addr: raft-0:5001
      - id: raft-1 
        addr: raft-1:5001
      - id: raft-2 
        addr: raft-2:5001

  runtime:
    heartbeat_interval: 100ms
    election_timeout_min: 500ms
    election_timeout_max: 1s

  transport:
    request_timeout: 300ms
